"""add_upi_id_to_user

Revision ID: 8124a023ac40
Revises: 810400730d39
Create Date: 2026-07-14 19:03:37.988372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8124a023ac40'
down_revision: Union[str, Sequence[str], None] = '810400730d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('upi_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'upi_id')
    # ### end Alembic commands ###
